Eswe 619 create kotlin model for json entity part2
ministryofjustice/hmpps-ciag-careers-induction-api pull request #8
Opened 2023-06-23 12:02 UTC by sacintha

2023-06-28 08:38 UTC, theDustRoom requested changes

2023-06-28 08:38 UTC, theDustRoom commented on src/main/resources/migration/V1_1__start.sql
> +    "ciagprofile_offender_id"     varchar(255) not null,
Why do we need another id when we have `offender_id`?

2023-06-28 08:38 UTC, theDustRoom commented on src/main/resources/migration/V1_1__start.sql
> +    "profile_offender_id" varchar(255),
Same here, why is this not just `offender_id`?

2023-06-29 08:28 UTC, sacintha commented on src/main/resources/migration/V1_1__start.sql
> +    "ciagprofile_offender_id"     varchar(255) not null,
Sorry this SQl was generated as a first round of test.Now have updated.

2023-06-29 08:28 UTC, sacintha commented on src/main/resources/migration/V1_1__start.sql
> +    "profile_offender_id" varchar(255),
Sorry this SQl was generated as a first round of test.Now have updated.

2023-07-04 08:04 UTC, theDustRoom approved these changes
LGTM

2023-07-04 08:04 UTC, merged